package:
  name: vcd-to-csv
  version: "{{ environ['VERSION'] }}"

source:
  git_url: https://github.com/KULeuven-MICAS/vcd-to-csv
  git_rev: main

requirements:
  build:
    - rust
  run:
    - libgcc-ng

about:
  home: https://github.com/KULeuven-MICAS/vcd-to-csv
  summary: "A utility to convert VCD files to CSV."
