name: Build conda package

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build conda package
        uses: prefix-dev/rattler-build-action@v0.2.23
        with:
          recipe-path: conda/meta.yaml
