name: Build conda package

on:
  push:
  release:
    types: [published]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build conda package
        uses: prefix-dev/rattler-build-action@v0.2.23
        with:
          recipe-path: conda/meta.yaml

      - name: Upload binary artifact
        uses: actions/upload-artifact@v3
        with:
          name: conda-package
          path: conda/output/linux-64/vcd-to-csv-*.conda
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: conda/output/linux-64/vcd-to-csv-*.conda
          asset_name: vcd-to-csv-0.1.0-0.tar.bz2
          asset_content_type: application/x-bzip2          
